version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL8DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  achat-backend:
    depends_on:
      - mysqldb
    image: wissalmetaadi/achat:2.0.0
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - 8089:8089
    stdin_open: true
    tty: true
  achat-front:
    depends_on: [achat-backend]
    image: wissalmetaadi/achatang:1.0  
    ports:
      - 80:80

volumes:
  db: